### ISSUE TITLE
Q: why not submit a PR to upstream?

### ISSUE THREAD

**Issue by Samira-El** [smarek/python-mariadb-replication#2]
Hello, wondering why not submit the support for mariadb's GTID to the [upstream repo](https://github.com/noplay/python-mysql-replication) as a PR?

**Comment by smarek** [comment]
@Samira-El never considered this, and I'd be happy with upstream support, could you do it instead please?

**Comment by Samira-El** [comment]
Thanks for the fast reply! will take that into consideration.

Curious as to how is this implementation faring in a production environment?
